
function Hero() {
    return (
        <div>
            <h1 className="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span className="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">Hashr</span> Secure passwords</h1>
            <p className="text-lg font-normal text-gray-500 lg:text-xl dark:text-gray-400">This is a webapp that can generate secure, unique and theft-resistant passwords for every website. Using the PwdHash algorithm created by Stanford University, it creates highly secure and strong passwords for all the websites you log into and keeps it safely stored on your mobile device. The password generated by the app will never be stored on a server or somewhere else so you can have peace of mind that all your passwords are safe.</p>
        </div>
    );
}

export default Hero;